# Generated by Django 5.0.9 on 2025-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0002_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner_profile',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='img_profile',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
