# Generated by Django 5.0.9 on 2025-05-03 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0006_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartida', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('es_publico', models.BooleanField(default=True)),
                ('publicacion_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidas', to='NexworkApp.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_compartidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
