# Generated by Django 5.0.9 on 2025-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0008_trabajo_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
