# Generated by Django 5.0.9 on 2025-05-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0011_educacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('habilidades_tecnicas', models.TextField(blank=True, null=True)),
                ('habilidades_blandas', models.TextField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('tiempo_completo', 'Tiempo completo'), ('medio_tiempo', 'Medio tiempo'), ('freelance', 'Freelance'), ('temporal', 'Temporal'), ('prácticas', 'Prácticas profesionales')], max_length=100, null=True)),
                ('salario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracion_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('idiomas', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('horario_laboral', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficios', models.TextField(blank=True, null=True)),
                ('disponibilidad_viajar', models.BooleanField(default=False)),
                ('disponibilidad_cambio_residencia', models.BooleanField(default=False)),
                ('numero_vacantes', models.PositiveIntegerField(default=1)),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='NexworkApp.trabajo')),
            ],
        ),
    ]
