# Generated by Django 5.0.9 on 2025-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0013_vistatrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistatrabajo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vistatrabajo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vistatrabajo',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
