# Generated by Django 5.0.9 on 2025-05-06 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0014_vistatrabajo_ciudad_vistatrabajo_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita de perfil',
                'verbose_name_plural': 'Visitas de perfiles',
                'ordering': ['-fecha'],
                'unique_together': {('perfil', 'visitante', 'fecha')},
            },
        ),
    ]
