# Generated by Django 5.0.9 on 2025-05-06 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexworkApp', '0015_visitaperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amistad', 'Amistad'), ('postulacion', 'Postulación'), ('comentario', 'Comentario'), ('like', 'Like'), ('compartido', 'Publicación compartida'), ('sistema', 'Sistema')], max_length=20)),
                ('mensaje', models.TextField()),
                ('url', models.CharField(blank=True, help_text='Enlace donde redirige la notificación', max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
